In [1]:
print("vishnu")

vishnu

In [6]:
!pip3 install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.4-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vishnu/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/vishnu/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 2.2 MB/s eta 0:00:00a 0:00:01m
Downloading numpy-2.3.4-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 2.5 MB/s eta 0:00:00a 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]
Successfully installed numpy-2.3.4 pandas-2.3.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip3 install --upgrade pip

In [8]:
import pandas as pd
print(pd.__version__)

2.3.3

In [9]:
import pandas as pd
data = pd.DataFrame(
    [[ 1, 2, "hi"],
    [3, 4, "ho"],
    [5, 6, "ha"],
    [7, 8, "hu"]],
    columns=['a', 'b', 'c']
)

In [6]:
data.shape

NameError: name 'data' is not defined

In [18]:
data.describe()

              a         b
count  4.000000  4.000000
mean   4.000000  5.000000
std    2.581989  2.581989
min    1.000000  2.000000
25%    2.500000  3.500000
50%    4.000000  5.000000
75%    5.500000  6.500000
max    7.000000  8.000000

In [21]:
print(data.head(2))

   a  b   c
0  1  2  hi
1  3  4  ho

In [25]:
data.a

0    1
1    3
2    5
3    7
Name: a, dtype: int64

In [27]:
data[0:2]

   a  b   c
0  1  2  hi
1  3  4  ho

In [5]:
print(data['c'])

NameError: name 'data' is not defined

In [4]:
data

NameError: name 'data' is not defined